version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini

  # queue:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile-queue
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app
  #     - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thegioithethao

  mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - '1080:1080'
